GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/torchaudio/backend/utils.py:54: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  '"sox" backend is being deprecated. '
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/2

  | Name    | Type | Params
---------------------------------
0 | encoder | CAVE | 13 M  
Traceback (most recent call last):
  File "/home/sgurram/Projects/cave_ml/train.py", line 97, in <module>
    train_cave()
  File "/home/sgurram/Projects/cave_ml/train.py", line 89, in train_cave
    trainer.fit(model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 282, in ddp_train
    results = self.train_or_test()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 466, in train
    self.run_sanity_check(self.get_model())
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 318, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 238, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, loader_name))
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 341, in request_dataloader
    dataloader = dataloader_fx()
  File "/home/sgurram/Projects/cave_ml/lightning.py", line 80, in val_dataloader
    dataset = AudioVisualData(data_type='val')
TypeError: __init__() got an unexpected keyword argument 'data_type'
Traceback (most recent call last):
  File "/home/sgurram/Projects/cave_ml/train.py", line 97, in <module>
    train_cave()
  File "/home/sgurram/Projects/cave_ml/train.py", line 89, in train_cave
    trainer.fit(model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 282, in ddp_train
    results = self.train_or_test()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 466, in train
    self.run_sanity_check(self.get_model())
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 648, in run_sanity_check
    self.reset_val_dataloader(ref_model)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 318, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._reset_eval_dataloader(model, 'val')
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 238, in _reset_eval_dataloader
    dataloaders = self.request_dataloader(getattr(model, loader_name))
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/pytorch_lightning/trainer/data_loading.py", line 